На данной странице представлен список моих личных книг из области программирования. В силу разных причин они мне более особо не нужны и выставлены на продажу. Все книги в единственном экземпляре. По мере продажи и поступления новых книг каталог периодически обновляется.

Продажа осуществляется на территории Великобритании. Оплата по Paypal. Доставка - Royal Mail. Прочие вопросы по данным книгам и их продаже можно задать по адресу itbooksale@gmail.com.

Цены очень низкие.

Приятных покупок.

.. _Купить: https://sites.google.com/site/russianitbooks/home/oformit-zakaz

-----

`Параллельное и распределенное программирование с использованием C++`__

__ http://www.ozon.ru/context/detail/id/1919696/

Parallel and Distributed Programming Using C++

Автор: Камерон Хьюз, Трейси Хьюз

Переводчик Н. Ручко

Издательство: Вильямс

ISBN 5-8459-0686-5, 0-13-101376-9

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000151057.jpg

Цена: 7 фунтов (+3 фунта доставка) - Купить_

-----

`Разработка ядра Linux`__

__ http://www.ozon.ru/context/detail/id/2918313/

Linux Kernel Development

Автор: Роберт Лав

Переводчик А. Судаков

Издательство: Вильямс

ISBN 5-8459-1085-4, 0-672-32720-1

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1001839089.jpg

Цена: 2 фунта (+3 фунта доставка) - Купить_

-----

`Изучаем Perl`__

__ http://www.ozon.ru/context/detail/id/89834/

Автор: Рэндал Л. Шварц, Том Кристиансен

Издательство: BHV - Санкт - Петербург

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/isuchaemperl99mkid.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Linux. Азбука ядра`__

__ http://www.ozon.ru/context/detail/id/3183301/

The Linux Kernel Primer: A Top-Down Approach for x86 and Power PC Architectures

Автор: Клаудия Зальзберг Родригес, Гордон Фишер, Стивен Смолски

Переводчик И. Легостаев

Издательство: КУДИЦ-Пресс

ISBN 978-5-91136-017-7, 0-596-00794-9

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000484316.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Perl. Библиотека программиста`__

__ http://www.ozon.ru/context/detail/id/92225/

Автор: Т. Кристиансен, Н. Торкингтон

Издательство: Питер

Серия: Библиотека программиста

ISBN 5-8046-0094-X, 1-56592-243-3

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/sv492_08.jpg

Цена: 2 фунта (+3 фунта доставка) - Купить_

-----

`Perl: специальный справочник`__

__ http://www.ozon.ru/context/detail/id/93948/

Автор: С. Холзнер

Издательство: Питер

ISBN 5-8046-0198-9

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/holznerperlspecsprav00sdg.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Ядро Linux`__

__ http://www.ozon.ru/context/detail/id/3589107/

Understanding the Linux Kernel

Автор: Д. Бовет, М. Чезати

Переводчик Сергей Иноземцев

Издательство: БХВ-Петербург

ISBN 0-596-00565-2, 978-5-94157-957-0

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000629115.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Параллельное программирование с использованием OpenMP`__

__ http://www.ozon.ru/context/detail/id/3997430/

Автор: М. П. Левин

Издательство: Интернет-университет информационных технологий, Бином. Лаборатория знаний

Серия: Основы информационных технологий

ISBN 978-5-94774-857-4

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1001610751.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Программист-прагматик. Путь от подмастерья к мастеру`__

__ http://www.ozon.ru/context/detail/id/1657382/

The Pragmatic Programmer: From Journeyman to Master

Автор: Э. Хант, Д. Томас

Переводчик А. Алексашин

Издательство: Лори, Питер Пресс

Серия: Библиотека программиста

ISBN 5-85582-213-3, 0-201-61622-X

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000110757.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Системное программирование на C++ для Unix`__

__ http://www.ozon.ru/context/detail/id/88398/

Автор: Теренс Чан

Издательство: BHV

ISBN 5-7315-0013-4, 0-13-331562-2

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/chansistemnprognacpppodunix99ttr.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Недокументированные и малоизвестные возможности Windows (+ CD-ROM)`__

__ http://www.ozon.ru/context/detail/id/2753056/

Автор: Роман Клименко

Издательство: Питер

Серия: Библиотека пользователя

ISBN 5-469-01562-9

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000368668.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Программирование на C++ глазами хакера (+ CD)`__

__ http://www.ozon.ru/context/detail/id/1917657/

Автор: Михаил Фленов

Издательство: БХВ-Петербург

ISBN 5-94157-500-9

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000164491.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Операционная система реального времени QNX Neutrino 6.3. Системная архитектура`__

__ http://www.ozon.ru/context/detail/id/2446329/

QNX Neutrino RTOS: System Architecture

Переводчик Ю. Асотов

Издательство: БХВ-Петербург

ISBN 5-94157-827-X

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000275572.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Системное программирование в Windows (+ CD-ROM)`__

__ http://www.ozon.ru/context/detail/id/2575245/

Автор: А. П. Побегайло

Издательство: БХВ-Петербург

Серия: В подлиннике

ISBN 5-94157-792-3

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000314623.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Библиотека QT4. Создание прикладных приложений в среде Linux`__

__ http://www.ozon.ru/context/detail/id/2764115/

Автор: А. В. Чеботарев

Издательство: Вильямс, Диалектика

Серия: Профессиональная работа

ISBN 5-8459-0996-1

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000372452.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`iPhone. Разработка приложений с открытым кодом`__

__ http://www.ozon.ru/context/detail/id/4385456/

iPhone Open Application Development

Автор: Джонатан Здзиарски

Переводчик Александра Маленкова

Издательство: БХВ-Петербург

ISBN 978-5-9775-0397-6, 978-0-596-15519-3

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1001075309.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Операционная система UNIX`__

__ http://www.ozon.ru/context/detail/id/2419365/

Автор: Андрей Робачевский, Сергей Немнюгин, Ольга Стесик

Издательство: БХВ-Петербург

ISBN 978-5-94157-538-1

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000265245.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Qt. Профессиональное программирование на C++. Наиболее полное руководство`__

__ http://www.ozon.ru/context/detail/id/2273393/

Автор: Макс Шлее

Издательство: БХВ-Петербург

Серия: В подлиннике

ISBN 5-94157-566-1

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000272392.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_

-----

`Qt 4. Программирование GUI на С++ (+ CDROM)`__

__ http://www.ozon.ru/context/detail/id/3356786/

C++ GUI Programming with Qt 4

Автор: Жасмин Бланшет, Марк Саммерфилд

Переводчик В. Казаченко

Издательство: КУДИЦ-Пресс

ISBN 978-5-91136-038-2, 0138722494

.. image:: http://mmedia.ozon.ru/multimedia/books_covers/c200/1000544572.jpg

Цена: 3 фунта (+3 фунта доставка) - Купить_
